
openapi: "3.0.0"

info:
  title: Drogon
  version: "1.0"
servers:
  - url: http://localhost:5000/

paths:
  /login:
    post:
      summary: Token login
      description: Token login
      operationId: routes.users.login
      responses:
        200:
          description: Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_data:
                  type: string