
openapi: "3.0.0"

info:
  title: Drogon
  version: "1.0"
servers:
  - url: http://localhost:5000/

paths:
  /login:
    post:
      summary: Token login
      description: Token login
      responses:
        200:
          description: Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                master_passwd:
                  type: string
                master_number:
                  type: integer
                username:
                  type: string
    put:
      summary: Register
      description: register
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string